version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: fleet_care_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleet_care_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_test_data:
